# Generated by Django 3.2.10 on 2022-01-14 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productPhoto1',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='productPhoto2',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='productPhoto3',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='productPhoto4',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='productPhoto5',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='productCategoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='shops.productcategory'),
        ),
    ]
