# Generated by Django 3.2.10 on 2022-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20220121_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shopBio',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopLocation',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
