# Generated by Django 3.2.10 on 2022-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20220121_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(default='N/A', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto1',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
    ]
