# Generated by Django 3.2.10 on 2022-01-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20220121_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='shopName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductAdmin', to='shops.shop'),
        ),
    ]
