# Generated by Django 3.2.10 on 2022-01-21 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0009_auto_20220121_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='ShopName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shopName',
            new_name='shop',
        ),
    ]
