# Generated by Django 3.2.10 on 2022-01-21 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0011_shopname_shopprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='productCategory',
            new_name='productCategoryName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productCategoryId',
        ),
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productCategory', to='shops.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='productOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(default='N/A', max_length=64)),
                ('shopProfile', models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d')),
                ('shopBio', models.CharField(default='N/A', max_length=255)),
                ('shopLocation', models.CharField(default='N/A', max_length=255)),
                ('shopOwner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shops.shop'),
        ),
        migrations.DeleteModel(
            name='ShopName',
        ),
    ]
