# Generated by Django 3.2.10 on 2022-01-21 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0012_auto_20220121_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productCategory', to='shops.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='productOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopBio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopLocation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
