# Generated by Django 3.2.10 on 2022-01-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0014_auto_20220122_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=64)),
                ('shopProfile', models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d')),
                ('shopBio', models.CharField(max_length=255)),
                ('shopLocation', models.CharField(max_length=255)),
                ('shopOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
