# Generated by Django 3.2.10 on 2022-01-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_alter_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productOwner',
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto1',
            field=models.FileField(max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto2',
            field=models.FileField(max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto3',
            field=models.FileField(max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto4',
            field=models.FileField(max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto5',
            field=models.FileField(max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopProfile',
            field=models.FileField(max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
    ]
