# Generated by Django 3.2.10 on 2022-01-23 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20220123_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shops.shop'),
        ),
    ]
