# Generated by Django 3.2.10 on 2022-01-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_alter_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPhoto1',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto2',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto3',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto4',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPhoto5',
            field=models.FileField(default='/media/pictures/2022/01/08/project-2.jpg', max_length=255, upload_to='pictures/%Y/%m/%d'),
        ),
    ]
